#define CATCH_CONFIG_MAIN
#include "catch.hpp"
#include "models/NodeTest.cpp"
#include "models/Arc2Test.cpp"
#include "models/Ising2dTest.cpp"
#include "algorithms/SimulatedAnnealingTest.cpp"
#include "models/Ising2dTransverseTest.cpp"
#include "algorithms/SantoroTosattiMartonakTest.cpp"
#include "algorithms/SwendsenWang.cpp"