#include "QMC-methods/SimulatedAnnealing.h"
#include "QMC-methods/SantoroTosattiMartonak.h"
#include "QMC-methods/SwendsenWang.h"
#include "QMC-methods/RiegerKawashimaContinuous.h"
#include "QMC-methods/RiegerKawashimaDiscrete.h"
